name: Frontend Check

on: [ push, pull_request ]

jobs:
  run-check:
    name: Frontend Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.1'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Start the frontend & check for a duration
        run: |
          cd frontend
          npm start > frontend.log 2>&1 &
          FRONTEND_PID=$!
          sleep 15
          
          if ! kill -0 $FRONTEND_PID 2>/dev/null; then
            echo "The frontend exited prematurely with errors. Here's the output:"
            cat frontend.log
            exit 1
          fi

      - name: Stop the frontend
        if: always()
        run: |
          kill $FRONTEND_PID || echo "Frontend already stopped."
